export const GET_ALBUM_INFO = 'GET_ALBUM_INFO';
export const SET_ALBUM_IMAGE_INDEX = 'SET_ALBUM_IMAGE_INDEX';
export const UPLOAD_ALBUM_IMAGE = 'UPLOAD_ALBUM_IMAGE';
export const UPLOAD_ALBUM_IMAGE_SUCCESS = 'UPLOAD_ALBUM_IMAGE_SUCCESS';
export const UPLOAD_ALBUM_IMAGE_FAIL = 'UPLOAD_ALBUM_IMAGE_FAIL';
export const CHANGE_ALBUM_INFO_SUCCESS = 'CHANGE_ALBUM_INFO_SUCCESS';
export const CHANGE_ALBUM_INFO_FAIL = 'CHANGE_ALBUM_INFO_FAIL';
export const CHANGE_ALBUM_INFO = 'CHANGE_ALBUM_INFO';
export const SUBMIT_ALBUM_INFO = 'SUBMIT_ALBUM_INFO';

export const GET_HOT_INFO = 'GET_HOT_INFO';
export const SET_HOT_IMAGE_INDEX = 'SET_HOT_IMAGE_INDEX';
export const UPLOAD_HOT_IMAGE = 'UPLOAD_HOT_IMAGE';
export const UPLOAD_HOT_IMAGE_SUCCESS = 'UPLOAD_HOT_IMAGE_SUCCESS';
export const UPLOAD_HOT_IMAGE_FAIL = 'UPLOAD_HOT_IMAGE_FAIL';
export const CHANGE_HOT_INFO_SUCCESS = 'CHANGE_HOT_INFO_SUCCESS';
export const CHANGE_HOT_INFO_FAIL = 'CHANGE_HOT_INFO_FAIL';
export const CHANGE_HOT_INFO = 'CHANGE_HOT_INFO';
export const SUBMIT_HOT_INFO = 'SUBMIT_HOT_INFO';

export const GET_TEACHERS_INFO = 'GET_TEACHERS_INFO';
export const SET_TEACHERS_INDEX = 'SET_TEACHERS_INDEX';
export const UPLOAD_TEACHERS_IAMGE = 'UPLOAD_TEACHERS_IAMGE';
export const UPLOAD_TEACHERS_IAMGE_SUCCESS = 'UPLOAD_TEACHERS_IAMGE_SUCCESS';
export const UPLOAD_TEACHERS_IAMGE_FAIL = 'UPLOAD_TEACHERS_IAMGE_FAIL';
export const CHANGE_TEACHERS_INFO = 'CHANGE_TEACHERS_INFO';
export const CHANGE_TEACHERS_INFO_SUCCESS = 'CHANGE_TEACHERS_INFO_SUCCESS';
export const CHANGE_TEACHERS_INFO_FAIL = 'CHANGE_TEACHERS_INFO_FAIL';
export const DELETE_TEACHERS_INTO = 'DELETE_TEACHERS_INTO';
export const SUBMIT_TEACHERS_INFO = 'SUBMIT_TEACHERS_INFO';
export const ADD_TEACHERS_INFO = 'ADD_TEACHERS_INFO';
export const ADD_TEACHERS_INFO_SUCCESS = 'ADD_TEACHERS_INFO_SUCCESS';
export const ADD_TEACHERS_INFO_FAIL = 'ADD_TEACHERS_INFO_FAIL';
export const SUBMIT_ADD_TEACHERS_INFO = 'SUBMIT_ADD_TEACHERS_INFO';

export const GET_EMAIL_INFO = 'GET_EMAIL_INFO';
export const DELETE_EMAIL = 'DELETE_EMAIL';

export const GET_JOIN_INFO = 'GET_JOIN_INFO';
export const DELETE_JOIN_PERSON = 'DELETE_JOIN_PERSON';

export const ADMIN_LOGIN = 'ADMIN_LOGIN';
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL';

export const GET_CLASS_INFO = 'GET_CLASS_INFO';
export const SUBMIT_CLASS_INFO = 'SUBMIT_CLASS_INFO';
export const CHANGE_CLASS_INFO = 'CHANGE_CLASS_INFO';
export const CHANGE_CLASS_INFO_SUCCESS = 'CHANGE_CLASS_INFO_SUCCESS';
export const CHANGE_CLASS_INFO_FAIL = 'CHANGE_CLASS_INFO_FAIL';

export const GET_PERSON_INFO = 'GET_PERSON_INFO';
export const SET_PERSON_INDEX = 'SET_PERSON_INDEX';
export const CHANGE_PERSON_INFO = 'CHANGE_PERSON_INFO';
export const CHANGE_PERSON_INFO_SUCCESS = 'CHANGE_PERSON_INFO_SUCCESS';
export const CHANGE_PERSON_INFO_FAIL = 'CHANGE_PERSON_INFO_FAIL';
export const DELETE_PERSON_INFO = 'DELETE_PERSON_INFO';
export const SUBMIT_PERSON_INFO = 'SUBMIT_PERSON_INFO';
export const UPLOAD_PERSON_IAMGE = 'UPLOAD_PERSON_IAMGE';
export const UPLOAD_PERSON_IAMGE_SUCCESS = 'UPLOAD_PERSON_IAMGE_SUCCESS';
export const UPLOAD_PERSON_IAMGE_FAIL = 'UPLOAD_PERSON_IAMGE_FAIL';
export const CHANGE_PERSON_SRC_INFO = 'CHANGE_PERSON_SRC_INFO';
export const SUBMIT_PERSON_SRC_INFO = 'SUBMIT_PERSON_SRC_INFO';
export const SUBMIT_PERSON_SRC_INFO_SUCCESS = 'SUBMIT_PERSON_SRC_INFO_SUCCESS';
export const SUBMIT_PERSON_SRC_INFO_FAIL = 'SUBMIT_PERSON_SRC_INFO_FAIL';
export const ADD_PERSON_INFO = 'ADD_PERSON_INFO';
export const ADD_PERSON_INFO_SUCCESS = 'ADD_PERSON_INFO_SUCCESS';
export const ADD_PERSON_INFO_FAIL = 'ADD_PERSON_INFO_FAIL';
export const SUBMIT_ADD_PERSON_INFO = 'SUBMIT_ADD_PERSON_INFO';

export const ADD_ARTICLE = 'ADD_ARTICLE';
export const ADD_ARTICLE_SUCCESS = 'ADD_ARTICLE_SUCCESS';
export const ADD_ARTICLE_FAIL = 'ADD_ARTICLE_FAIL';
export const GET_ARTICLE_INFO = 'GET_ARTICLE_INFO';
export const GET_ARTICLE_INFO_SUCCESS = 'GET_ARTICLE_INFO_SUCCESS';
export const GET_ARTICLE_INFO_FAIL = 'GET_ARTICLE_INFO_FAIL';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';