export const GET_ALBUM_INFO = 'GET_ALBUM_INFO';
export const SET_ALBUM_IMAGE_INDEX = 'SET_ALBUM_IMAGE_INDEX';
export const UPLOAD_ALBUM_IMAGE = 'UPLOAD_ALBUM_IMAGE';
export const UPLOAD_ALBUM_IMAGE_SUCCESS = 'UPLOAD_ALBUM_IMAGE_SUCCESS';
export const UPLOAD_ALBUM_IMAGE_FAIL = 'UPLOAD_ALBUM_IMAGE_FAIL';
export const CHANGE_ALBUM_INFO_SUCCESS = 'CHANGE_ALBUM_INFO_SUCCESS';
export const CHANGE_ALBUM_INFO_FAIL = 'CHANGE_ALBUM_INFO_FAIL';
export const CHANGE_ALBUM_INFO = 'CHANGE_ALBUM_INFO';
export const SUBMIT_ALBUM_INFO = 'SUBMIT_ALBUM_INFO';

export const GET_HOT_INFO = 'GET_HOT_INFO';
export const SET_HOT_IMAGE_INDEX = 'SET_HOT_IMAGE_INDEX';
export const UPLOAD_HOT_IMAGE = 'UPLOAD_HOT_IMAGE';
export const UPLOAD_HOT_IMAGE_SUCCESS = 'UPLOAD_HOT_IMAGE_SUCCESS';
export const UPLOAD_HOT_IMAGE_FAIL = 'UPLOAD_HOT_IMAGE_FAIL';
export const CHANGE_HOT_INFO_SUCCESS = 'CHANGE_HOT_INFO_SUCCESS';
export const CHANGE_HOT_INFO_FAIL = 'CHANGE_HOT_INFO_FAIL';
export const CHANGE_HOT_INFO = 'CHANGE_HOT_INFO';
export const SUBMIT_HOT_INFO = 'SUBMIT_HOT_INFO';

export const GET_TEACHERS_INFO = 'GET_TEACHERS_INFO';

export const GET_EMAIL_INFO = 'GET_EMAIL_INFO';
export const DELETE_EMAIL = 'DELETE_EMAIL';

export const GET_JOIN_INFO = 'GET_JOIN_INFO';
export const DELETE_JOIN_PERSON = 'DELETE_JOIN_PERSON'

